Update aws-miniflux.yaml
pulumi/registry pull request #1062
Opened 2022-06-13 01:53 UTC by susanev

2022-06-13 07:07 UTC, cnunciato requested changes
This current package name is correct; it’s not an AWS service, it just happens to be written to run on AWS. (The other pages should be changed to reflect this.)

It does raise an interesting question though of what sort of convention we should use for these kinds of components. Probably something we should discuss.

2022-06-13 20:54 UTC, cnunciato commented
> @cnunciato what do you mean the other pages? the package page heading is currently AWS Miniflux, this is wrong? would Miniflux on AWS work for you?
> 
> As a note, almost all the other components are named in the format the current Miniflux package page is named.

Yep, this is why I bring it up. I'm not sure [Cloud] [Package] is the best display-naming convention for packages that aren't tied to a provider-specific offering. This convention definitely works for packages that _are_ tied to a provider-specific product, like AWS IAM, AWS API Gateway, EKS, etc., as "IAM", "API Gateway", and so on are all AWS products. But it doesn't quite work for things like Miniflux or "static website", applications or concepts exist separate from any one provider. 

Particularly when listed alongside packages like AWS EKS and the like, "AWS Miniflux" reads a bit like it could be an AWS managed service; similarly, "Azure Justrun" -- I had to go digging to find out whether "Justrun" was an Azure service or some other, more generic concept implemented for deployment on Azure. For generic/non-provider-specific things like these, we should probably consider an alternative display-naming convention. Your suggestion of "Miniflux on AWS" (or "Static website on AWS") seem clear to me, yeah, so that could be one way to go. Another might be to let display names just remain provider agnostic as they are now, which would allow us to list multiple "Miniflux" packages on the same page with a clear distinction of some sort to distinguish them from one another cloud-wise.

cc @lukehoban @stack72 who may have thoughts & opinions on this as well. (I don't have strong opinions myself other than wanting to keep things as clear and unambiguous as we can.)

2022-06-14 01:14 UTC, susanev commented
@cnunciato can you open up a new issue instead related to component naming? seems a bit weird to include that In this pr which was only trying to fix the misaligning between the package name and the name shown on the browse page. ill close the pr since you don't support it.

2022-06-14 01:15 UTC, closed without merging

2022-06-14 16:56 UTC, cnunciato commented
Sure thing. Meantime, here's a PR that I think accomplishes what you were after with this one (i.e., align the display names for this package): https://github.com/pulumi/registry/pull/1072