Publish Package metadata for pulumiverse/pulumi-clickhouse
pulumi/registry pull request #5051
Opened 2024-07-29 22:33 UTC by callicles

## Description

Adds pulumi-clickhouse to the registry

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

2024-07-30 08:13 UTC, ringods requested changes
@callicles small request:

* The `layout` in `docs/installation-configuration.md` should also be set to `package`. ([Source](https://github.com/pulumiverse/pulumi-clickhouse/blob/e3a7cee8ea559ed244394fd9437fca199772415c/docs/installation-configuration.md#L4))

After fixing this, please make a new release that incorporates this change.

2024-07-30 16:44 UTC, callicles commented
@ringods Thank you for the review!

Fixed and released

2024-07-31 07:17 UTC, ringods approved these changes

2024-07-31 14:10 UTC, cnunciato approved these changes

2024-07-31 14:17 UTC, merged