Add 1Password Pulumi Provider to community packages
pulumi/registry pull request #5279
Opened 2024-08-27 17:33 UTC by edif2008

## Description

This PR adds the [1Password provider for Pulumi](https://github.com/1Password/pulumi-onepassword) to the Pulumi Registry.

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [x] a description that explains what the package does.
  - [ ] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [ ] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [ ] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

2024-08-28 08:51 UTC, ringods requested changes
@edif2008 Can you update the following attributes to refer to 1Password (the company)?

* [DisplayName](https://github.com/1Password/pulumi-onepassword/blob/main/provider/resources.go#L64): Preferrably set it to `1Password`. This will be used in our registry instead of the regular `Name` property having value `onepassword`.
* [Publisher](https://github.com/1Password/pulumi-onepassword/blob/main/provider/resources.go#L69): we don't manage your provider, so the value shouldn't be `Pulumi`.
* [Homepage](https://github.com/1Password/pulumi-onepassword/blob/main/provider/resources.go#L86): Should point to your website
* [LogoURL](https://github.com/1Password/pulumi-onepassword/blob/main/provider/resources.go#L75): This is the logo which is used in our registry, as well as the logo used when publishing the packages in the package registries. Contrary to the comment above this line, it should preferrably be a PNG image because nuget.org doesn't accept SVG.

The `copyable command for installing the plugin binary` has an example here:

https://github.com/pulumiverse/pulumi-grafana/blob/main/docs/installation-configuration.md#provider-binary

Please add an adapted version of this command to your `docs/installation-configuration.md` file.

Please drop the `XXXXXXX` placeholder in the [CLI command for setting the token](https://github.com/1Password/pulumi-onepassword/blob/main/docs/installation-configuration.md?plain=1#L41). Doing it that way stores the token value unencrypted in your shell history! 

The preferred way is this:

```sh
$ pulumi config set pulumi-onepassword:service_account_token --secret
Value: <paste token here>
```

2024-08-28 16:36 UTC, edif2008 commented
A question I have about the LogoURL. What if we don't have any? Or at most only SVG? 🤔

2024-08-29 16:29 UTC, edif2008 commented
@ringods We've updated the metadata and made a new release with it.

2024-08-30 06:16 UTC, ringods approved these changes

2024-09-03 13:58 UTC, merged