Update checklist for community package contributions
pulumi/registry pull request #6209
Opened 2024-12-11 23:40 UTC by mjeffryes

## Description

We want all new packages added to the registry to support all core Pulumi languages and to have an identified maintainer contact. This PR adds those items to the PR checklist.

2024-12-11 23:46 UTC, guineveresaenger requested changes
Should we require Java? Why/why not?

2024-12-11 23:46 UTC, guineveresaenger commented on .github/pull_request_template.md
> +  - [ ] at least one representative example in all supported languages (ie. ts/js, python, go and c#).
What about Java? this would still retain a discrepancy between all official Pulumi languages and what's required here.

2024-12-11 23:46 UTC, guineveresaenger commented on .github/pull_request_template.md
> +  - [ ] at least one representative example in all supported languages (ie. ts/js, python, go and c#).
```suggestion
  - [ ] at least one representative example in all supported languages (i.e. TypeScript, Python, Go and C#).
```

2024-12-11 23:46 UTC, guineveresaenger commented on .github/pull_request_template.md
> +  - [ ] links to SDKs in all supported languages (ie. should link to published SDKs in NPM, PyPi and NuGet).
```suggestion
  - [ ] links to SDKs in all supported languages (i.e. should link to published SDKs in NPM, PyPi and NuGet).
```

2024-12-11 23:49 UTC, guineveresaenger approved these changes

2024-12-11 23:50 UTC, mjeffryes commented
Hmmm... I'm inclined to give package maintainers a pass on Java because it's represents a pretty tiny slice of users and we know from experience that publishing packages for Java is a pain. I'd really like to be able to offer publishing support for package authors so they would not need to jump through hoops for even NPM, PyPi and NuGet. Hopeful that we'll get there one day.

2024-12-12 10:41 UTC, iwahbe reviewed
This is a major pain to authors. Why don't we allow them to use parameterized providers instead of published SDKs?

2024-12-12 14:34 UTC, mjeffryes commented
> This is a major pain to authors. Why don't we allow them to use parameterized providers instead of published SDKs?

I don't quite follow you here? I assume you mean letting them just include docs for how to use with local package support? Two concerns with that:
1) Doesn't work for native providers or components
2) If they are explicitly bridging a TF provider, the APIs likely won't align; I'd rather just advertise the local packages based docs for all languages

2024-12-12 21:29 UTC, mjeffryes commented
> I keep forgetting that [pulumi/pulumi#17056](https://github.com/pulumi/pulumi/issues/17056) isn't in yet. I'll come back to this proposal when [pulumi/pulumi#17056](https://github.com/pulumi/pulumi/issues/17056) is closed.

Sounds good! I agree it would be way better not to have to force publishing woes on everyone who wants to add a package to the registry!

2024-12-12 21:29 UTC, merged